name = "cloud-gallery"

compatibility_date = "2022-07-25"
compatibility_flags = [
  "streams_enable_constructors",
  "transformstream_enable_standard_constructor",
]
# The SSR code is generated in the `server` directory.
main = "server/entry.ssr.js"
# assets = { bucket = "./dist", include = ["**", "../../header/dist/**"] }
assets = "./dist"
# Build the SSR code that will run in the Worker.
[build]
# The client code is generated in the `dist` directory.
# We use the `assets` config to supply these static files as needed.
command = "npm run build"
# Rebuild when the helper library changes
watch_dir = ["src", "../helpers/src"]

[env.test]
name = "cloud-gallery-test"
account_id = "bdf08bcf300a4c3dbabf7f873954e79d"
workers_dev = true

[[services]]
binding = "header"
service = "cloud-gallery-header-test"
[[services]]
binding = "gallery"
service = "cloud-gallery-gallery-test"
[[services]]
binding = "filter"
service = "cloud-gallery-filter-test"
[[services]]
binding = "body"
service = "cloud-gallery-body-test"
[[services]]
binding = "footer"
service = "cloud-gallery-footer-test"

[env.prod]
name = "cloud-gallery"
account_id = "bdf08bcf300a4c3dbabf7f873954e79d"

[[services]]
binding = "header"
service = "cloud-gallery-header"
[[services]]
binding = "gallery"
service = "cloud-gallery-gallery"
[[services]]
binding = "filter"
service = "cloud-gallery-filter"
[[services]]
binding = "body"
service = "cloud-gallery-body"
[[services]]
binding = "footer"
service = "cloud-gallery-footer"
