name = "qwik-workers-body"

compatibility_date = "2022-07-25"
compatibility_flags = [
  "streams_enable_constructors",
  "transformstream_enable_standard_constructor",
]
# The SSR code is generated in the `server` directory.
main = "server/entry.ssr.js"
# assets = { bucket = "./dist", include = ["**", "../../header/dist/**"] }
assets = "./dist"
# Build the SSR code that will run in the Worker.
[build]
# The client code is generated in the `dist` directory.
# We use the `assets` config to supply these static files as needed.
command = "npm run build"
# Rebuild when the helper library changes
watch_dir = ["src", "../helpers/src"]
[env.prod]
name = "qwik-workers-body"
[env.test]
name = "qwik-workers-body-test"
