name: Qwik Workers Prod
on:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  qwik-workers-prod:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.1.x

      - name: Install
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${secrets.GITHUB_TOKEN}

      - name: Run tests
        run: npm run check

      - name: Deploy
        run: npm run deploy:prod
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
